# Generated by Django 2.2.6 on 2019-10-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_act', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('hora_inicio', models.DateTimeField(auto_now=True)),
                ('duracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=30, unique=True)),
                ('correo', models.EmailField(max_length=50)),
                ('tipo', models.CharField(choices=[('A', 'administrador'), ('N', 'natural')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioNatural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('fecha_nacimiento', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='app.UsuarioNatural')),
                ('receptor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='app.UsuarioNatural')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('R', 'realizando'), ('F', 'finalizado')], default='R', max_length=1)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actividad')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UsuarioNatural')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actividad')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo', to='app.UsuarioNatural')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.UsuarioNatural')),
            ],
        ),
    ]
