# Generated by Django 2.2.6 on 2019-11-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='hora_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='hash',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarionatural',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
    ]
