# Generated by Django 2.2.7 on 2019-11-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amistad',
            name='amigo_id',
        ),
        migrations.RemoveField(
            model_name='amistad',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='act_id',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='act_id',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='emisor_id',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='receptor_id',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Amistad',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
