# Generated by Django 2.2.7 on 2019-11-30 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20191130_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_act', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('hora_inicio', models.DateTimeField()),
                ('duracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to=settings.AUTH_USER_MODEL)),
                ('receptor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('R', 'realizando'), ('F', 'finalizado')], default='R', max_length=1)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actividad')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actividad')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
